services:
  api:
    image: crossword-server
    environment:
      - DB_URL=${DB_URL}
      - GIN_MODE=release
      - DSN=https://514620b5bde14216af129b62e81ffb0e@o370716.ingest.sentry.io/5181475
    restart: always
    profiles: ["production"]
  scraper:
    image: crossword-server
    environment:
      - DB_URL=${DB_URL}
      - GIN_MODE=release
      - DSN=https://514620b5bde14216af129b62e81ffb0e@o370716.ingest.sentry.io/5181475
    entrypoint: /bin/scraper.bin
    profiles: ["production"]
    restart: always
  scraper:
    image: crossword-server
    environment:
      - DB_URL=${DB_URL}
      - GIN_MODE=release
      - DSN=https://514620b5bde14216af129b62e81ffb0e@o370716.ingest.sentry.io/5181475
    entrypoint: /bin/scrapeall.bin
    profiles: ["scrapeall"]
  web:
    image: crossword-frontend-server
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=https://crossword.theodoretliu.com/api
    profiles: ["production"]
  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: always
    ports:
      - 80:80
      - 443:443
    profiles: ["production"]
  dev-database:
    restart: always
    image: postgres:16
    ports:
      - "20001:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    profiles: ["dev"]
